layout_spectrum: 1
color:
  saturation: 0.8521304
  lightness: 0.8276942
  brandStrength: 1
  brandColors:
    - '#5CA34A'
    - '#F2FFF3'
    - '#BCE9B5'
  rhythmicContrast: 0.9022557
typography_spectrum: 0.9135338
name: Sell my home
